Audio Processing Framework (APF): apf::CommandQueue Class Reference
apf::CommandQueue Class Reference
Manage command queue from non-realtime thread to realtime thread.
#include <apf/commandqueue.h>
Classes
struct Command
Abstract base class for realtime commands.
class WaitCommand
Dummy command to synchronize with non-realtime thread.
Public Member Functions
Functions to be called from the non-realtime thread
If there are multiple non-realtime threads, access has to be locked!
CommandQueue (size_t size)
Constructor.
~CommandQueue ()
Destructor.
void push (Command *cmd)
Push a command to be executed in the realtime thread.
void wait ()
Wait for realtime thread.
void cleanup_commands ()
Clean up all commands in the cleanup-queue.
bool deactivate ()
Deactivate queue; process following commands in the non-realtime thread.
void reactivate ()
Re-activate queue.
Functions to be called from the realtime thread
void process_commands ()
Execute all commands in the queue.
bool commands_available () const
Check if commands are available.
Detailed Description
Manage command queue from non-realtime thread to realtime thread.
Commands can be added in the non-realtime thread with push().
Commands are executed when process_commands() is called from the realtime thread.
Definition at line 47 of file commandqueue.h.
Constructor & Destructor Documentation
apf::CommandQueue::CommandQueue (size_t size) inline explicit
Constructor.
Parameters
size maximum number of commands in queue.
Definition at line 87 of file commandqueue.h.
apf::CommandQueue::~CommandQueue () inline
Destructor.
Attention
Commands in the cleanup queue are cleaned up, but commands in the process queue are ignored and their memory is not freed!
Definition at line 96 of file commandqueue.h.
References cleanup_commands(), push(), and wait().
Member Function Documentation
void apf::CommandQueue::push (Command * cmd) inline
Push a command to be executed in the realtime thread.
The command will be cleaned up when it comes back from the realtime thread. If the CommandQueue is inactive, the command is not queued but executed and cleaned up immediately.
Parameters
cmd The command to be executed.
Definition at line 191 of file commandqueue.h.
References cleanup_commands(), and apf::CommandQueue::Command::execute().
Referenced by wait(), and ~CommandQueue().
void apf::CommandQueue::wait () inline
Wait for realtime thread.
Push an empty command and wait for its return.
Definition at line 218 of file commandqueue.h.
References cleanup_commands(), and push().
Referenced by ~CommandQueue().
void apf::CommandQueue::cleanup_commands () inline
Clean up all commands in the cleanup-queue.
Note
This function must be called from the non-realtime thread.
Definition at line 109 of file commandqueue.h.
Referenced by deactivate(), push(), reactivate(), wait(), and ~CommandQueue().
bool apf::CommandQueue::deactivate () inline
Deactivate queue; process following commands in the non-realtime thread.
Returns
true on success
Note
The queue must be empty. If not, the queue is not deactivated and false is returned.
Definition at line 120 of file commandqueue.h.
References cleanup_commands().
Referenced by apf::MimoProcessor< Derived, interface_policy, thread_policy, query_policy >::MimoProcessor().
void apf::CommandQueue::reactivate () inline
Re-activate queue.
See also
deactivate().
Definition at line 128 of file commandqueue.h.
References cleanup_commands().
void apf::CommandQueue::process_commands () inline
Execute all commands in the queue.
After execution, the commands are queued for cleanup in the non-realtime thread.
Note
This function must be called from the realtime thread.
Definition at line 144 of file commandqueue.h.
References apf::CommandQueue::Command::execute().
Referenced by apf::MimoProcessor< Derived, interface_policy, thread_policy, query_policy >::~MimoProcessor().
bool apf::CommandQueue::commands_available () const inline
Check if commands are available.
Returns
true if commands are available.
Definition at line 160 of file commandqueue.h.
References apf::CommandQueue::Command::cleanup().
The documentation for this class was generated from the following file:
apf/commandqueue.h