Audio Processing Framework (APF): apf::has_begin_and_end< I > Class Template Reference
apf::has_begin_and_end< I > Class Template Reference
Convenience class providing begin() and end().
#include <apf/iterator.h>
Public Types
using iterator = I
using reference = typename std::iterator_traits< I >::reference
using difference_type = typename std::iterator_traits< I >::difference_type
Public Member Functions
has_begin_and_end ()
Default constructor. Singular iterators are created.
has_begin_and_end (iterator b, iterator e)
Constructor with begin and end.
template<typename Distance >
has_begin_and_end (iterator b, Distance length)
Constructor with begin and length.
iterator begin () const
Get begin.
iterator end () const
Get end.
reference operator[] (difference_type n) const
Subscript operator.
Protected Attributes
iterator _begin
iterator _end
Detailed Description
template<typename I>
class apf::has_begin_and_end< I >
Convenience class providing begin() and end().
The derived class can manipulate the protected members _begin and _end.
Warning
If you use this as base class, don't use a base class pointer (or reference). This class has a public non-virtual destructor, which is generally not recommended for base classes.
Definition at line 331 of file iterator.h.
Constructor & Destructor Documentation
template<typename I> apf::has_begin_and_end< I >::has_begin_and_end () inline
Default constructor. Singular iterators are created.
Definition at line 339 of file iterator.h.
template<typename I> apf::has_begin_and_end< I >::has_begin_and_end (iterator b, iterator e) inline
Constructor with begin and end.
Definition at line 342 of file iterator.h.
template<typename I> template<typename Distance > apf::has_begin_and_end< I >::has_begin_and_end (iterator b, Distance length) inline
Constructor with begin and length.
Definition at line 346 of file iterator.h.
Member Function Documentation
template<typename I> iterator apf::has_begin_and_end< I >::begin () const inline
Get begin.
Note
There is no const-ness propagation. The const-ness of the original iterator I is maintained.
Definition at line 358 of file iterator.h.
Referenced by apf::make_circular_iterator().
template<typename I> iterator apf::has_begin_and_end< I >::end () const inline
Get end.
Note
There is no const-ness propagation. The const-ness of the original iterator I is maintained.
Definition at line 363 of file iterator.h.
Referenced by apf::make_circular_iterator().
template<typename I> reference apf::has_begin_and_end< I >::operator[] (difference_type n) const inline
Subscript operator.
Note
This only works if I is a random access iterator!
Definition at line 367 of file iterator.h.
Referenced by apf::stride_iterator< channel_iterator >::stride_iterator().
The documentation for this class was generated from the following file:
apf/iterator.h