Audio Processing Framework (APF): apf::conv::TransformBase Class Reference
apf::conv::TransformBase Class Reference
Forward-FFT-related functions.
#include <apf/convolver.h>
Public Member Functions
template<typename In >
void prepare_filter (In first, In last, Filter &filter) const
Transform time-domain samples.
size_t block_size () const
size_t partition_size () const
template<typename In >
In prepare_partition (In first, In last, fft_node &partition) const
FFT of one block.
Protected Types
using scoped_plan = fftw< float >::scoped_plan
using plan_ptr = std::unique_ptr< scoped_plan >
Protected Member Functions
TransformBase (size_t block_size_)
TransformBase (TransformBase &&)=default
plan_ptr _create_plan (float *array) const
Create in-place FFT plan for halfcomplex data format.
void _fft (float *first) const
In-place FFT.
Protected Attributes
plan_ptr _fft_plan
Detailed Description
Forward-FFT-related functions.
Definition at line 126 of file convolver.h.
Member Function Documentation
prepare_filter()
template<typename In > void apf::conv::TransformBase::prepare_filter (In first, In last, Filter & filter) const
Transform time-domain samples.
If there are too few input samples, the rest is zero-padded, if there are too few blocks in the container c, the rest of the samples is ignored.
Parameters
first Iterator to first time-domain sample
last Past-the-end iterator
[out] filter Target container
Definition at line 198 of file convolver.h.
References prepare_partition().
Referenced by apf::conv::Filter::Filter().
prepare_partition()
template<typename In > In apf::conv::TransformBase::prepare_partition (In first, In last, fft_node & partition) const
FFT of one block.
If there are too few coefficients, the rest is zero-padded.
Parameters
first Iterator to first coefficient
last Past-the-end iterator
[out] partition Target partition
Template Parameters
In Forward iterator
Returns
Iterator to the first coefficient of the next block (for the next iteration, if needed)
Definition at line 217 of file convolver.h.
References _fft(), apf::math::has_only_zeros(), and apf::conv::fft_node::zero.
Referenced by prepare_filter().
_create_plan()
TransformBase::plan_ptr apf::conv::TransformBase::_create_plan (float * array) const protected
Create in-place FFT plan for halfcomplex data format.
Note
FFT plans are not re-entrant except when using FFTW_THREADSAFE!
Once a plan of a certain size exists, creating further plans is very fast because "wisdom" is shared (and therefore the creation of plans is not thread-safe). It is not necessary to re-use plans in other convolver instances.
Definition at line 183 of file convolver.h.
Referenced by apf::conv::Input::Input().
_fft()
void apf::conv::TransformBase::_fft (float * first) const inline protected
In-place FFT.
Definition at line 150 of file convolver.h.
Referenced by apf::conv::Input::add_block(), and prepare_partition().
The documentation for this class was generated from the following file:
apf/convolver.h