Audio Processing Framework (APF): apf::jack_policy Class Reference
apf::jack_policy Class Reference abstract
Policies
interface_policy using JACK.
#include <apf/jack_policy.h>
Public Types
using sample_type = sample_t
Public Types inherited from apf::JackClient
enum callback_usage_t { dont_use_jack_process_callback = 0, use_jack_process_callback }
Select if JACK's audio callback function shall be called.
typedef jack_default_audio_sample_t sample_t
typedef jack_nframes_t nframes_t
typedef jack_port_t port_t
Public Member Functions
nframes_t block_size () const
Public Member Functions inherited from apf::JackClient
JackClient (const std::string &name="JackClient", callback_usage_t callback_usage=dont_use_jack_process_callback)
Constructor.
bool activate () const
Activate JACK client.
bool deactivate () const
Deactivate JACK client.
bool set_freewheel (int onoff) const
Set JACK freewheeling mode.
std::string client_name () const
nframes_t sample_rate () const
nframes_t buffer_size () const
bool is_realtime () const
int get_real_time_priority () const
float get_cpu_load () const
pthread_t client_thread_id () const
port_t * register_in_port (const std::string &name) const
Register JACK input port.
port_t * register_out_port (const std::string &name) const
Register JACK output port.
port_t * register_port (const std::string &name, unsigned long flags) const
Register JACK port (input or output).
bool unregister_port (port_t *port) const
Unregister JACK port.
bool connect_ports (const std::string &source, const std::string &destination) const
Connect two JACK ports.
bool disconnect_ports (const std::string &source, const std::string &destination) const
Disconnect two JACK ports.
bool connect_pending_connections () const
Make connections which are still pending from a previous call to connect_ports().
void transport_start () const
Start JACK transport.
void transport_stop () const
Stop JACK transport.
bool transport_locate (nframes_t frame) const
Set JACK transport location.
std::pair< bool, nframes_t > get_transport_state () const
Get JACK transport state.
Protected Member Functions
jack_policy (const parameter_map &p=parameter_map())
Constructor.
Protected Member Functions inherited from apf::JackClient
virtual void jack_shutdown_callback (jack_status_t code, const char *reason)
JACK shutdown callback.
virtual int jack_sample_rate_callback (nframes_t sr)
JACK sample rate callback.
virtual int jack_buffer_size_callback (nframes_t bs)
JACK buffer size callback.
virtual int jack_xrun_callback ()
JACK xrun callback.
Detailed Description
interface_policy using JACK.
Some of the functions are directly taken from JackClient.
See also
MimoProcessor
Definition at line 52 of file jack_policy.h.
Constructor & Destructor Documentation
apf::jack_policy::jack_policy (const parameter_map & p = parameter_map()) inline explicit protected
Constructor.
Parameters
p Parameters, only the parameter "name" (for the name of the JACK client) is supported.
Definition at line 69 of file jack_policy.h.
References apf::str::A2S(), apf::parameter_map::get(), apf::parameter_map::has_key(), apf::JackClient::register_in_port(), and apf::JackClient::register_out_port().
The documentation for this class was generated from the following file:
apf/jack_policy.h