Audio Processing Framework (APF): apf::cast_iterator< T, I > Class Template Reference
apf::cast_iterator< T, I > Class Template Reference
Iterators
Iterator that casts items to T* on dereferenciation.
#include <apf/iterator.h>
Public Types
using value_type = T
using pointer = T *
using reference = T &
using difference_type = typename std::iterator_traits< I >::difference_type
using iterator_category = typename std::iterator_traits< I >::iterator_category
Public Member Functions
cast_iterator (I base_iterator)
Constructor from base iterator.
cast_iterator ()
Default constructor.
reference operator* () const
Dereference operator.
pointer operator-> () const
Arrow operator.
reference operator[] (difference_type n) const
Subscript operator.
bool operator== (const self &rhs) const
Straightforward equality operator.
self & operator++ ()
Straightforward preincrement operator.
self & operator-- ()
Straightforward predecrement operator.
self & operator+= (difference_type n)
Straightforward addition/assignment operator.
self operator++ (int)
Postincrement operator (using preincrement operator).
self operator-- (int)
Postdecrement operator (using predecrement operator).
bool operator!= (const self &rhs) const
Unequality operator (using equality operator).
self operator+ (difference_type n) const
Addition operator (iterator plus integer, using +=).
self & operator-= (difference_type n)
Subtraction/assignment operator (using +=).
self operator- (difference_type n) const
Subtraction operator (using +=).
I base () const
Get the base iterator, inspired by std::reverse_iterator::base().
Friends
bool operator< (const self &lhs, const self &rhs)
Straightforward less-than operator.
difference_type operator- (const self &lhs, const self &rhs)
Straightforward difference operator.
bool operator> (const self &lhs, const self &rhs)
Straightforward greater-than operator (using less-than operator).
bool operator<= (const self &lhs, const self &rhs)
Straightforward less-or-equal operator (using less-than operator).
bool operator>= (const self &lhs, const self &rhs)
Straightforward greater-or-equal operator (using less-than operator).
self operator+ (difference_type n, const self &it)
Addition operator (integer plus iterator, using +=).
Detailed Description
template<typename T, typename I>
class apf::cast_iterator< T, I >
Iterator that casts items to T* on dereferenciation.
There is an extra dereference inside the dereference operator, similar to boost::indirect_iterator (http://boost.org/doc/libs/release/libs/iterator/doc/indirect_iterator.html). But before that, the pointer is casted to the desired type T.
Template Parameters
T Pointee type to be casted to
I Base iterator type
Precondition
value_type of I must be a pointer to a compatible type!
See also
make_cast_iterator() (helper function)
cast_proxy, cast_proxy_const
Definition at line 523 of file iterator.h.
Constructor & Destructor Documentation
cast_iterator() [1/2]
template<typename T , typename I > apf::cast_iterator< T, I >::cast_iterator (I base_iterator) inline explicit
Constructor from base iterator.
Parameters
base_iterator base iterator
Definition at line 536 of file iterator.h.
cast_iterator() [2/2]
template<typename T , typename I > apf::cast_iterator< T, I >::cast_iterator () inline
Default constructor.
Note
This constructor creates a singular iterator. Another cast_iterator can be assigned to it, but nothing else works.
Definition at line 536 of file iterator.h.
References apf::no_nullptr().
Member Function Documentation
operator*()
template<typename T , typename I > reference apf::cast_iterator< T, I >::operator* () const inline
Dereference operator.
Returns
Reference to current item, casted to T.
Definition at line 542 of file iterator.h.
operator->()
template<typename T , typename I > pointer apf::cast_iterator< T, I >::operator-> () const inline
Arrow operator.
Returns
Pointer to current item, casted to T.
Definition at line 550 of file iterator.h.
References apf::no_nullptr().
operator[]()
template<typename T , typename I > reference apf::cast_iterator< T, I >::operator[] (difference_type n) const inline
Subscript operator.
Parameters
n index
Returns
Reference to n-th item, casted to T.
Definition at line 560 of file iterator.h.
References apf::no_nullptr().
operator==()
template<typename T , typename I > bool apf::cast_iterator< T, I >::operator== (const self & rhs) const inline
Straightforward equality operator.
Definition at line 567 of file iterator.h.
operator++() [1/2]
template<typename T , typename I > self& apf::cast_iterator< T, I >::operator++ () inline
Straightforward preincrement operator.
Definition at line 569 of file iterator.h.
operator--() [1/2]
template<typename T , typename I > self& apf::cast_iterator< T, I >::operator-- () inline
Straightforward predecrement operator.
Definition at line 570 of file iterator.h.
operator+=()
template<typename T , typename I > self& apf::cast_iterator< T, I >::operator+= (difference_type n) inline
Straightforward addition/assignment operator.
Definition at line 571 of file iterator.h.
operator++() [2/2]
template<typename T , typename I > self apf::cast_iterator< T, I >::operator++ (int) inline
Postincrement operator (using preincrement operator).
Definition at line 573 of file iterator.h.
operator--() [2/2]
template<typename T , typename I > self apf::cast_iterator< T, I >::operator-- (int) inline
Postdecrement operator (using predecrement operator).
Definition at line 574 of file iterator.h.
operator!=()
template<typename T , typename I > bool apf::cast_iterator< T, I >::operator!= (const self & rhs) const inline
Unequality operator (using equality operator).
Definition at line 575 of file iterator.h.
operator+()
template<typename T , typename I > self apf::cast_iterator< T, I >::operator+ (difference_type n) const inline
Addition operator (iterator plus integer, using +=).
Definition at line 577 of file iterator.h.
operator-=()
template<typename T , typename I > self& apf::cast_iterator< T, I >::operator-= (difference_type n) inline
Subtraction/assignment operator (using +=).
Definition at line 577 of file iterator.h.
operator-()
template<typename T , typename I > self apf::cast_iterator< T, I >::operator- (difference_type n) const inline
Subtraction operator (using +=).
Definition at line 577 of file iterator.h.
base()
template<typename T , typename I > I apf::cast_iterator< T, I >::base () const inline
Get the base iterator, inspired by std::reverse_iterator::base().
Definition at line 579 of file iterator.h.
Friends And Related Function Documentation
operator<
template<typename T , typename I > bool operator< (const self & lhs, const self & rhs) friend
Straightforward less-than operator.
Definition at line 568 of file iterator.h.
operator-
template<typename T , typename I > difference_type operator- (const self & lhs, const self & rhs) friend
Straightforward difference operator.
Definition at line 572 of file iterator.h.
operator>
template<typename T , typename I > bool operator> (const self & lhs, const self & rhs) friend
Straightforward greater-than operator (using less-than operator).
Definition at line 576 of file iterator.h.
operator<=
template<typename T , typename I > bool operator<= (const self & lhs, const self & rhs) friend
Straightforward less-or-equal operator (using less-than operator).
Definition at line 576 of file iterator.h.
operator>=
template<typename T , typename I > bool operator>= (const self & lhs, const self & rhs) friend
Straightforward greater-or-equal operator (using less-than operator).
Definition at line 576 of file iterator.h.
operator+
template<typename T , typename I > self operator+ (difference_type n, const self & it) friend
Addition operator (integer plus iterator, using +=).
Definition at line 577 of file iterator.h.
The documentation for this class was generated from the following file:
apf/iterator.h