Audio Processing Framework (APF): apf::BlockDelayLine< T, Container > Class Template Reference
apf::BlockDelayLine< T, Container > Class Template Reference
Block-based delay line.
#include <apf/blockdelayline.h>
Public Types
using size_type = typename Container::size_type
using pointer = typename Container::pointer
using circulator = apf::circular_iterator< typename Container::iterator >
Public Member Functions
BlockDelayLine (size_type block_size, size_type max_delay)
Constructor.
bool delay_is_valid (size_type delay, size_type &corrected) const
Check if a given delay is valid.
bool delay_is_valid (size_type delay) const
Return true if delay is valid.
void advance ()
Advance the internal iterators/pointers to the next block.
template<typename Iterator >
void write_block (Iterator source)
Write a block of data to the delay line.
template<typename Iterator >
bool read_block (Iterator destination, size_type delay) const
Read a block of data from the delay line.
template<typename Iterator >
bool read_block (Iterator destination, size_type delay, T weight) const
Read from the delay line and multiply each element by a given factor.
pointer get_write_pointer () const
Get the write pointer.
circulator get_read_circulator (size_type delay=0) const
Get the read circulator.
Protected Member Functions
circulator _get_data_circulator () const
Get a circular iterator to the sample with time 0.
Protected Attributes
const size_type _block_size
Size of read/write blocks.
Detailed Description
template<typename T, typename Container = std::vector<T>>
class apf::BlockDelayLine< T, Container >
Block-based delay line.
This is a "write once, read many times" delay line. The write operation is simple and fast. The desired delay is specified at the more flexible read operation.
Definition at line 44 of file blockdelayline.h.
Constructor & Destructor Documentation
template<typename T , typename Container > apf::BlockDelayLine< T, Container >::BlockDelayLine (size_type block_size, size_type max_delay)
Constructor.
Parameters
block_size Block size
max_delay Maximum delay in samples
Definition at line 117 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::_block_size.
Member Function Documentation
template<typename T, typename Container = std::vector<T>> bool apf::BlockDelayLine< T, Container >::delay_is_valid (size_type delay, size_type & corrected) const inline
Check if a given delay is valid.
Parameters
delay Desired delay
[out] corrected If valid, the same as delay, if not, the maximum possible delay.
Returns
true if delay is valid.
Definition at line 58 of file blockdelayline.h.
Referenced by apf::BlockDelayLine< T, Container >::delay_is_valid(), apf::NonCausalBlockDelayLine< T, Container >::delay_is_valid(), and apf::BlockDelayLine< T, Container >::read_block().
template<typename T, typename Container = std::vector<T>> bool apf::BlockDelayLine< T, Container >::delay_is_valid (size_type delay) const inline
Return true if delay is valid.
See also
delay_is_valid()
Definition at line 66 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::delay_is_valid().
template<typename T, typename Container = std::vector<T>> void apf::BlockDelayLine< T, Container >::advance () inline
Advance the internal iterators/pointers to the next block.
Definition at line 73 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::_block_size, apf::BlockDelayLine< T, Container >::get_read_circulator(), apf::BlockDelayLine< T, Container >::get_write_pointer(), apf::BlockDelayLine< T, Container >::read_block(), and apf::BlockDelayLine< T, Container >::write_block().
Referenced by apf::NonCausalBlockDelayLine< T, Container >::NonCausalBlockDelayLine(), and apf::BlockDelayLine< T, Container >::write_block().
template<typename T , typename Container > template<typename Iterator > void apf::BlockDelayLine< T, Container >::write_block (Iterator source)
Write a block of data to the delay line.
Before writing, the read and write pointers are advanced to the next block. If you don't want to use this function, you can also call advance(), get the write pointer with get_write_pointer() and write directly to it.
Parameters
source Pointer/iterator where the block of data shall be read from.
Attention
In source there must be enough data to read from!
Note
source must be a random access iterator. If you want to use another iterator, you'll have to do it on your own (as written above).
Definition at line 147 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::_block_size, apf::BlockDelayLine< T, Container >::advance(), and apf::BlockDelayLine< T, Container >::get_write_pointer().
Referenced by apf::BlockDelayLine< T, Container >::advance(), and apf::NonCausalBlockDelayLine< T, Container >::NonCausalBlockDelayLine().
template<typename T , typename Container > template<typename Iterator > bool apf::BlockDelayLine< T, Container >::read_block (Iterator destination, size_type delay) const
Read a block of data from the delay line.
Parameters
destination Iterator to destination
delay Delay in samples
Returns
true on success
Definition at line 162 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::_block_size, apf::BlockDelayLine< T, Container >::delay_is_valid(), and apf::BlockDelayLine< T, Container >::get_read_circulator().
Referenced by apf::BlockDelayLine< T, Container >::advance().
template<typename T , typename Container > template<typename Iterator > bool apf::BlockDelayLine< T, Container >::read_block (Iterator destination, size_type delay, T weight) const
Read from the delay line and multiply each element by a given factor.
Definition at line 177 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::_block_size, apf::BlockDelayLine< T, Container >::delay_is_valid(), and apf::BlockDelayLine< T, Container >::get_read_circulator().
template<typename T , typename Container > BlockDelayLine< T, Container >::pointer apf::BlockDelayLine< T, Container >::get_write_pointer () const
Get the write pointer.
Attention
Before the write operation, advance() must be called to update read and write pointers.
You must not write more than one block with this pointer! For the next block, you have to get a new pointer.
Definition at line 195 of file blockdelayline.h.
Referenced by apf::BlockDelayLine< T, Container >::advance(), apf::NonCausalBlockDelayLine< T, Container >::NonCausalBlockDelayLine(), and apf::BlockDelayLine< T, Container >::write_block().
template<typename T , typename Container > BlockDelayLine< T, Container >::circulator apf::BlockDelayLine< T, Container >::get_read_circulator (size_type delay = 0) const
Get the read circulator.
Parameters
delay Delay in samples
Attention
There is no check if the delay is in the valid range between 0 and max_delay. You are responsible for checking that!
Definition at line 207 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::_get_data_circulator().
Referenced by apf::BlockDelayLine< T, Container >::advance(), and apf::BlockDelayLine< T, Container >::read_block().
template<typename T, typename Container = std::vector<T>> circulator apf::BlockDelayLine< T, Container >::_get_data_circulator () const inline protected
Get a circular iterator to the sample with time 0.
Definition at line 94 of file blockdelayline.h.
Referenced by apf::BlockDelayLine< T, Container >::get_read_circulator().
Member Data Documentation
template<typename T, typename Container = std::vector<T>> const size_type apf::BlockDelayLine< T, Container >::_block_size protected
Size of read/write blocks.
Definition at line 96 of file blockdelayline.h.
Referenced by apf::BlockDelayLine< T, Container >::advance(), apf::BlockDelayLine< T, Container >::BlockDelayLine(), apf::BlockDelayLine< T, Container >::read_block(), and apf::BlockDelayLine< T, Container >::write_block().
The documentation for this class was generated from the following file:
apf/blockdelayline.h