Audio Processing Framework (APF): apf::NonCausalBlockDelayLine< T, Container > Class Template Reference
apf::NonCausalBlockDelayLine< T, Container > Class Template Reference
A block-based delay line where negative delay is possible.
#include <apf/blockdelayline.h>
Public Types
using difference_type = typename _base::circulator::difference_type
using size_type = typename Container::size_type
using circulator = apf::circular_iterator< typename Container::iterator >
Public Member Functions
NonCausalBlockDelayLine (size_type block_size, size_type max_delay, size_type initial_delay)
Constructor.
void advance ()
template<typename Iterator >
void write_block (Iterator source)
pointer get_write_pointer () const
bool delay_is_valid (difference_type delay, difference_type &corrected) const
Check if a given delay is valid.
bool delay_is_valid (difference_type delay) const
Return true if delay is valid.
template<typename Iterator >
bool read_block (Iterator destination, difference_type delay) const
template<typename Iterator >
bool read_block (Iterator destination, difference_type delay, T weight) const
circulator get_read_circulator (difference_type delay=0) const
Detailed Description
template<typename T, typename Container = std::vector<T>>
class apf::NonCausalBlockDelayLine< T, Container >
A block-based delay line where negative delay is possible.
This is done by delaying everything by a given initial delay. The (absolute value of the) negative delay can be at most as large as the initial delay.
See also
BlockDelayLine
Definition at line 224 of file blockdelayline.h.
Constructor & Destructor Documentation
NonCausalBlockDelayLine()
template<typename T , typename Container = std::vector<T>> apf::NonCausalBlockDelayLine< T, Container >::NonCausalBlockDelayLine (size_type block_size, size_type max_delay, size_type initial_delay) inline
Constructor.
Parameters
initial_delay initial delay
block_size Block size
max_delay Maximum delay in samples
initial_delay Additional delay to achieve negative delay
See also
BlockDelayLine::BlockDelayLine()
Definition at line 239 of file blockdelayline.h.
Member Function Documentation
advance()
template<typename T , typename Container = std::vector<T>> void apf::NonCausalBlockDelayLine< T, Container >::advance ()
See also
BlockDelayLine::advance()
write_block()
template<typename T , typename Container = std::vector<T>> template<typename Iterator > void apf::NonCausalBlockDelayLine< T, Container >::write_block (Iterator source)
See also
BlockDelayLine::write_block()
get_write_pointer()
template<typename T , typename Container = std::vector<T>> pointer apf::NonCausalBlockDelayLine< T, Container >::get_write_pointer () const
See also
BlockDelayLine::get_write_pointer()
delay_is_valid() [1/2]
template<typename T , typename Container = std::vector<T>> bool apf::NonCausalBlockDelayLine< T, Container >::delay_is_valid (difference_type delay, difference_type & corrected) const inline
Check if a given delay is valid.
Parameters
delay Desired delay
[out] corrected If valid, the same as delay, if too low/high, the minimum/maximum possible delay, respectively.
Returns
true if delay is valid.
See also
BlockDelayLine::delay_is_valid()
Definition at line 266 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::delay_is_valid().
Referenced by apf::NonCausalBlockDelayLine< T, Container >::delay_is_valid().
delay_is_valid() [2/2]
template<typename T , typename Container = std::vector<T>> bool apf::NonCausalBlockDelayLine< T, Container >::delay_is_valid (difference_type delay) const inline
Return true if delay is valid.
See also
delay_is_valid()
Definition at line 281 of file blockdelayline.h.
References apf::NonCausalBlockDelayLine< T, Container >::delay_is_valid().
read_block() [1/2]
template<typename T , typename Container = std::vector<T>> template<typename Iterator > bool apf::NonCausalBlockDelayLine< T, Container >::read_block (Iterator destination, difference_type delay) const inline
See also
BlockDelayLine::read_block()
Definition at line 289 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::read_block().
read_block() [2/2]
template<typename T , typename Container = std::vector<T>> template<typename Iterator > bool apf::NonCausalBlockDelayLine< T, Container >::read_block (Iterator destination, difference_type delay, T weight) const inline
See also
BlockDelayLine::read_block()
Definition at line 298 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::read_block().
get_read_circulator()
template<typename T , typename Container = std::vector<T>> circulator apf::NonCausalBlockDelayLine< T, Container >::get_read_circulator (difference_type delay = 0) const inline
See also
BlockDelayLine::get_read_circulator()
Definition at line 306 of file blockdelayline.h.
References apf::BlockDelayLine< T, Container >::get_read_circulator().
The documentation for this class was generated from the following file:
apf/blockdelayline.h