Audio Processing Framework (APF): Iterators
Iterators
TODO: overview of iterators?
Classes
class apf::accumulating_iterator< I >
An output iterator which adds on assignment.
class apf::cast_iterator< T, I >
Iterator that casts items to T* on dereferenciation.
class apf::circular_iterator< I >
Circular iterator class.
class apf::transform_iterator< I, F >
Iterator adaptor with a function call at dereferenciation.
class apf::index_iterator< T >
Iterator with a built-in number.
class apf::stride_iterator< I >
A stride iterator.
class apf::dual_iterator< I1, I2 >
Iterate over two iterators at once.
class apf::discard_iterator
An iterator which does nothing.
Functions
template<typename I >
accumulating_iterator< I > apf::make_accumulating_iterator (I base_iterator)
Helper function to create an accumulating_iterator.
template<typename T , typename I >
cast_iterator< T, I > apf::make_cast_iterator (I base_iterator)
Helper function to create a cast_iterator.
template<typename I >
circular_iterator< I > apf::make_circular_iterator (I begin, I end)
Helper function to create a circular_iterator.
template<typename I >
circular_iterator< I > apf::make_circular_iterator (I begin, I end, I current)
Helper function to create a circular_iterator.
template<typename I , typename F >
transform_iterator< I, F > apf::make_transform_iterator (I base_iterator, F f)
Helper function to create a transform_iterator.
template<typename T >
index_iterator< T > apf::make_index_iterator (T start)
Helper function to create an index_iterator.
template<typename I1 , typename I2 >
dual_iterator< I1, I2 > apf::make_dual_iterator (I1 i1, I2 i2)
Helper function to create an dual_iterator.
Detailed Description
TODO: overview of iterators?
See also
Iterator macros
Function Documentation
template<typename I > accumulating_iterator<I> apf::make_accumulating_iterator (I base_iterator)
Helper function to create an accumulating_iterator.
The template parameter is optional because it can be inferred from the parameter base_iterator. Example:
make_accumulating_iterator(some_iterator)
Parameters
base_iterator the base iterator
Returns
an accumulating_iterator
Definition at line 502 of file iterator.h.
Referenced by apf::CombineChannelsBase< CombineChannels< L, Out >, L, Out >::process().
template<typename T , typename I > cast_iterator<T, I> apf::make_cast_iterator (I base_iterator)
Helper function to create a cast_iterator.
The second template parameter is optional because it can be inferred from the parameter base_iterator. Example:
make_cast_iterator<my_target_type>(some_iterator)
Parameters
base_iterator the base iterator
Returns
a cast_iterator
Definition at line 603 of file iterator.h.
template<typename I > circular_iterator<I> apf::make_circular_iterator (I begin, I end)
Helper function to create a circular_iterator.
The template parameter is optional because it can be inferred from the parameter(s). Example:
make_circular_iterator(some_begin, some_end)
Parameters
some_begin the first iterator
some_end past-the-end iterator
Returns
a circular_iterator
Definition at line 837 of file iterator.h.
References apf::has_begin_and_end< I >::begin(), and apf::has_begin_and_end< I >::end().
template<typename I > circular_iterator<I> apf::make_circular_iterator (I begin, I end, I current)
Helper function to create a circular_iterator.
The template parameter is optional because it can be inferred from the parameter(s). Example:
make_circular_iterator(some_begin, some_end, some_current)
Parameters
some_begin the first iterator
some_end past-the-end iterator
some_current current iterator
Returns
a circular_iterator
Definition at line 854 of file iterator.h.
References apf::has_begin_and_end< I >::begin(), and apf::has_begin_and_end< I >::end().
template<typename I , typename F > transform_iterator<I, F> apf::make_transform_iterator (I base_iterator, F f)
Helper function to create a transform_iterator.
The template parameters are optional because they can be inferred from the parameters base_iterator and f. Example:
make_transform_iterator(some_iterator, some_function)
Parameters
base_iterator the base iterator
f the function (normally a function object)
Returns
a transform_iterator
Definition at line 941 of file iterator.h.
template<typename T > index_iterator<T> apf::make_index_iterator (T start)
Helper function to create an index_iterator.
The template parameter is optional because it can be inferred from the parameter start. Example:
make_index_iterator(42)
Parameters
start the start index
Returns
an index_iterator
Definition at line 1031 of file iterator.h.
template<typename I1 , typename I2 > dual_iterator<I1, I2> apf::make_dual_iterator (I1 i1, I2 i2)
Helper function to create an dual_iterator.
The template parameters are optional because they can be inferred from the parameters i1 and i2. Example:
apf::make_dual_iterator(some_iterator, some_other_iterator)
Parameters
i1 one base iterator
i2 another base iterator
Returns
a dual_iterator
Definition at line 1331 of file iterator.h.