Audio Processing Framework (APF): apf::mex Namespace Reference
apf::mex Namespace Reference
Helper functions for creating MEX files.
Functions
bool convert (const mxArray *in, std::string &out)
Convert mxArray to std::string.
bool convert (const mxArray *in, double &out)
Convert mxArray to double.
bool convert (const mxArray *in, int &out)
Convert mxArray to int.
bool convert (const mxArray *in, bool &out)
Convert mxArray to bool.
bool convert (const mxArray *in, size_t &out)
Convert mxArray to size_t.
bool convert (const mxArray *in, std::map< std::string, std::string > &out)
Convert mxArray to a std::map of std::strings.
bool convert (const mxArray *in, std::vector< std::string > &out)
Convert mxArray to a std::vector of std::strings.
template<typename T >
bool next_arg (int &n, const mxArray **&p, T &data)
Get next argument, converted to T.
template<typename T >
bool next_optarg (int &n, const mxArray **&p, T &data)
Get next optional argument, converted to T.
template<typename T >
void next_arg (int &n, const mxArray **&p, T &data, const std::string &error)
Get next argument, converted to T.
template<typename T >
void next_optarg (int &n, const mxArray **&p, T &data, const std::string &error)
Get next optional argument, converted to T.
Detailed Description
Helper functions for creating MEX files.
Function Documentation
bool apf::mex::convert (const mxArray * in, std::string & out)
Convert mxArray to std::string.
Definition at line 112 of file mextools.h.
Referenced by convert().
bool apf::mex::convert (const mxArray * in, double & out)
Convert mxArray to double.
Definition at line 124 of file mextools.h.
bool apf::mex::convert (const mxArray * in, int & out)
Convert mxArray to int.
Definition at line 133 of file mextools.h.
bool apf::mex::convert (const mxArray * in, bool & out)
Convert mxArray to bool.
Definition at line 144 of file mextools.h.
bool apf::mex::convert (const mxArray * in, size_t & out)
Convert mxArray to size_t.
Definition at line 153 of file mextools.h.
bool apf::mex::convert (const mxArray * in, std::map< std::string, std::string > & out)
Convert mxArray to a std::map of std::strings.
This expects a scalar structure! Values must be real scalar numbers or strings!
Warning
In case of a conversion error, the map may be partially filled!
Definition at line 168 of file mextools.h.
References apf::str::A2S(), and convert().
bool apf::mex::convert (const mxArray * in, std::vector< std::string > & out)
Convert mxArray to a std::vector of std::strings.
This expects a cell array of strings!
Warning
In case of a conversion error, the vector may be partly filled!
Definition at line 206 of file mextools.h.
References convert().
template<typename T > bool apf::mex::next_arg (int & n, const mxArray **& p, T & data)
Get next argument, converted to T.
Parameters
[in,out] n Number of arguments, typically nrhs
[in,out] p Pointer to arguments, typically prhs
[out] data If conversion is successful, the result is stored here
Returns
true if argument was available and if conversion was successful
Postcondition
If conversion was successful, n is decremented and p is incremented. If not, n and p are unchanged, data may be corrupted.
Definition at line 254 of file mextools.h.
Referenced by next_arg().
template<typename T > bool apf::mex::next_optarg (int & n, const mxArray **& p, T & data)
Get next optional argument, converted to T.
Parameters
[in,out] data Default value. If there is an argument left and if the conversion is successful, the result is stored here.
Returns
true if no argument available or if conversion was successful
Postcondition
If an argument was available and its conversion was successful, the result is stored in data, n is decremented and p is incremented. If the conversion failed, n and p are unchanged, data may be corrupted. If there was no argument available, n, p and data are unchanged.
See also
next_arg()
Definition at line 270 of file mextools.h.
Referenced by next_optarg().
template<typename T > void apf::mex::next_arg (int & n, const mxArray **& p, T & data, const std::string & error)
Get next argument, converted to T.
See also
next_arg()
Parameters
error Message to be displayed on error
Definition at line 279 of file mextools.h.
References next_arg().
template<typename T > void apf::mex::next_optarg (int & n, const mxArray **& p, T & data, const std::string & error)
Get next optional argument, converted to T.
See also
next_optarg()
Parameters
error Message to be displayed on error
Definition at line 288 of file mextools.h.
References next_optarg().