Audio Processing Framework (APF): apf::math Namespace Reference
apf::math Namespace Reference
Mathematical constants and helper functions.
Classes
struct identity
Identity function object. Function call returns a const reference to input.
class linear_interpolator
Function object for linear interpolation.
class raised_cosine
Raised cosine (function object).
Functions
template<typename T >
constexpr T pi ()
.
template<>
constexpr float pi< float > ()
.
template<>
constexpr double pi< double > ()
.
template<>
constexpr long double pi< long double > ()
.
template<typename T >
T pi_div_180 ()
template<typename T >
T square (T x)
Product of a number with itself.
template<typename T >
T dB2linear (T L, bool power=false)
Convert a level in decibel to a linear gain factor.
template<typename T >
T linear2dB (T x, bool power=false)
Convert a linear gain factor to a level in dB.
template<typename T >
T deg2rad (T angle)
Convert an angle in degrees to an angle in radians.
template<typename T >
T rad2deg (T angle)
Convert an angle in radians to an angle in degrees.
template<typename T >
T fwrap (T x, T full)
Wrap x into the interval [0, full).
template<typename T >
T wrap (T x, T full)
Wrap x into the interval [0, full).
template<>
float wrap (float x, float full)
Wrap x into the interval [0, full).
template<>
double wrap (double x, double full)
Wrap x into the interval [0, full).
template<>
long double wrap (long double x, long double full)
Wrap x into the interval [0, full).
template<typename T >
T wrap_two_pi (T x)
template<typename T >
T next_power_of_2 (T number)
Find a power of 2 which is >= a given number.
template<typename I >
std::iterator_traits< I >::value_type max_amplitude (I begin, I end)
Return the absolute maximum of a series of numbers.
template<typename I >
std::iterator_traits< I >::value_type rms (I begin, I end)
Root Mean Square (RMS) value of a series of numbers.
template<typename I >
bool has_only_zeros (I first, I last)
Check if there are only zeros in a range.
template<typename T >
linear_interpolator< T > make_linear_interpolator (T first, T last)
Helper function for automatic template type deduction.
template<typename T , typename U >
linear_interpolator< T, U > make_linear_interpolator (T first, T last, U length)
Helper function for automatic template type deduction.
Detailed Description
Mathematical constants and helper functions.
Function Documentation
pi()
template<typename T > constexpr T apf::math::pi () constexpr
.
Undefined general case.
pi< float >()
template<> constexpr float apf::math::pi< float > () constexpr
.
Specialization for float.
Definition at line 51 of file math.h.
pi< double >()
template<> constexpr double apf::math::pi< double > () constexpr
.
Specialization for double.
Definition at line 61 of file math.h.
pi< long double >()
template<> constexpr long double apf::math::pi< long double > () constexpr
.
Specialization for long double.
Definition at line 69 of file math.h.
pi_div_180()
template<typename T > T apf::math::pi_div_180 () inline
Definition at line 76 of file math.h.
square()
template<typename T > T apf::math::square (T x) inline
Product of a number with itself.
Parameters
x number (any numeric type)
Returns
x squared.
Definition at line 87 of file math.h.
dB2linear()
template<typename T > T apf::math::dB2linear (T L, bool power = false) inline
Convert a level in decibel to a linear gain factor.
Parameters
L level
power if true, a factor of 10 is used, if false (default), the factor is 20.
Returns
the linear counterpart to L.
Definition at line 96 of file math.h.
linear2dB()
template<typename T > T apf::math::linear2dB (T x, bool power = false) inline
Convert a linear gain factor to a level in dB.
Parameters
x gain factor
power if true, a factor of 10 is used, if false (default), the factor is 20.
Returns
the logarithmic counterpart to x.
Attention
returns -Inf for x=0 and NaN for x<0.
Definition at line 111 of file math.h.
deg2rad()
template<typename T > T apf::math::deg2rad (T angle) inline
Convert an angle in degrees to an angle in radians.
Parameters
angle dito
Returns
angle in radians.
Definition at line 122 of file math.h.
rad2deg()
template<typename T > T apf::math::rad2deg (T angle) inline
Convert an angle in radians to an angle in degrees.
Parameters
angle dito
Returns
angle in degrees.
Definition at line 132 of file math.h.
fwrap()
template<typename T > T apf::math::fwrap (T x, T full) inline
Wrap x into the interval [0, full).
Helper function for float, double and long double.
See also
wrap()
Definition at line 141 of file math.h.
Referenced by wrap().
wrap() [1/4]
template<typename T > T apf::math::wrap (T x, T full) inline
Wrap x into the interval [0, full).
Unspecialized case, works only for integral types.
Definition at line 151 of file math.h.
Referenced by apf::circular_iterator< typename Container::iterator >::operator+=().
wrap() [2/4]
template<> float apf::math::wrap (float x, float full) inline
Wrap x into the interval [0, full).
Template specialization for float.
Definition at line 161 of file math.h.
References fwrap().
wrap() [3/4]
template<> double apf::math::wrap (double x, double full) inline
Wrap x into the interval [0, full).
Template specialization for double.
Definition at line 169 of file math.h.
References fwrap().
wrap() [4/4]
template<> long double apf::math::wrap (long double x, long double full) inline
Wrap x into the interval [0, full).
Template specialization for long double.
Definition at line 177 of file math.h.
References fwrap().
next_power_of_2()
template<typename T > T apf::math::next_power_of_2 (T number) inline
Find a power of 2 which is >= a given number.
Parameters
number number for which to find next power of 2
Returns
power of 2 above (or equal to) number
Note
For all numbers <= 1 the result is 1;
Definition at line 196 of file math.h.
max_amplitude()
template<typename I > std::iterator_traits<I>::value_type apf::math::max_amplitude (I begin, I end) inline
Return the absolute maximum of a series of numbers.
Parameters
begin beginning of range
end end of range
Returns
maximum, this is always >= 0.
Definition at line 210 of file math.h.
rms()
template<typename I > std::iterator_traits<I>::value_type apf::math::rms (I begin, I end) inline
Root Mean Square (RMS) value of a series of numbers.
Parameters
begin beginning of range
end end of range
Returns
RMS value
Definition at line 223 of file math.h.
has_only_zeros()
template<typename I > bool apf::math::has_only_zeros (I first, I last)
Check if there are only zeros in a range.
Returns
false as soon as a non-zero value is encountered
Definition at line 238 of file math.h.
Referenced by apf::conv::Input::add_block(), and apf::conv::TransformBase::prepare_partition().
make_linear_interpolator() [1/2]
template<typename T > linear_interpolator<T> apf::math::make_linear_interpolator (T first, T last)
Helper function for automatic template type deduction.
Definition at line 318 of file math.h.
make_linear_interpolator() [2/2]
template<typename T , typename U > linear_interpolator<T, U> apf::math::make_linear_interpolator (T first, T last, U length)
Helper function for automatic template type deduction.
Definition at line 326 of file math.h.