Audio Processing Framework (APF): apf::CommandQueue::Command Struct Reference
apf::CommandQueue::Command Struct Reference abstract
Abstract base class for realtime commands.
#include <apf/commandqueue.h>
Public Member Functions
virtual ~Command ()
Empty virtual destructor.
virtual void execute ()=0
The actual implementation of the command.
virtual void cleanup ()=0
Cleanup of resources.
Public Member Functions inherited from apf::NonCopyable
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=default
NonCopyable & operator= (NonCopyable &&)=default
Additional Inherited Members
Protected Member Functions inherited from apf::NonCopyable
NonCopyable ()=default
Protected default constructor.
~NonCopyable ()=default
Protected non-virtual destructor.
Detailed Description
Abstract base class for realtime commands.
These commands are passed through queues into the realtime thread and after execution back to the non-realtime thread for cleanup.
Definition at line 53 of file commandqueue.h.
Constructor & Destructor Documentation
virtual apf::CommandQueue::Command::~Command () inline virtual
Empty virtual destructor.
Definition at line 56 of file commandqueue.h.
References cleanup(), and execute().
Member Function Documentation
virtual void apf::CommandQueue::Command::execute () pure virtual
The actual implementation of the command.
This is called from the realtime thread. Overwritten in the derived class.
Implemented in apf::RtList< T * >::ClearCommand, apf::RtList< T * >::RemCommand, and apf::RtList< T * >::AddCommand.
Referenced by apf::CommandQueue::process_commands(), apf::CommandQueue::push(), apf::CommandQueue::WaitCommand::WaitCommand(), and ~Command().
virtual void apf::CommandQueue::Command::cleanup () pure virtual
Cleanup of resources.
This is called from the non-realtime thread. Overwritten in the derived class.
Implemented in apf::RtList< T * >::ClearCommand, apf::RtList< T * >::RemCommand, and apf::RtList< T * >::AddCommand.
Referenced by apf::CommandQueue::commands_available(), apf::CommandQueue::WaitCommand::WaitCommand(), and ~Command().
The documentation for this struct was generated from the following file:
apf/commandqueue.h